import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import styles from './layout.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className={styles.main_layout}>
              <Navbar/>
              <div className={styles.layout}>
                {children}
              </div>
              <Footer/>
        </main>
      </body>
    </html>
  )
}
